<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #faced5;
        }
    </style>
</head>
<body>

<h2 style="text-align: center">Welcome to AuthorsList</h2>

<?php
///* @var Listing $block */
//
//use ScienceSoft\Authors\Block\Listing;
//
//$authorsList = $block->getAllAuthors();

use ScienceSoft\Authors\ViewModel\Listing;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Listing $viewModel
 */

$viewModel = $block->getViewModel();
$authorsList = $viewModel->getAllAuthors();

?>
<h3 style="text-align: center">List of authors</h3>
<br>
<div style="display: flex; justify-content: space-around">
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Id_author</div>
        <div>
            <?php foreach ($authorsList as $item): ?>
                <div style="color: #2774a7; font-size: 16px"><?= $item->getId() ?></div>
            <?php endforeach; ?>
        </div>
    </div>
    <div style="display: flex; flex-direction: column">
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Name</div>
        <?php foreach ($authorsList as $item): ?>
            <?php if ($item['surname'] === null) { ?>
                <a style="color: #2774a7; font-size: 16px"
                   href="/author_page/<?= $item['identity']; ?>"><?= $item->getName(); ?></a>
            <?php } else { ?>
                <a style="color: #2774a7; font-size: 16px"
                   href="/author_page/<?= $item['identity']; ?>"><?= $item['name']; ?> <?= $item['surname']; ?></a>
            <?php } ?>
        <?php endforeach; ?>
    </div>
</div>

</body>
</html>
