<?php
/* @var View $block */

use ScienceSoft\Authors\Block\View;

$author = $block->getAuthor();
$book = $author->getExtensionAttributes()->getBook();
?>

<h2 style="text-align: center">All information about author</h2>
<br>

<div style="display: flex; justify-content: space-around">
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Id_author</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getId() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Name</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getName() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Surname</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getSurname() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Date</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getDate() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Status</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getStatus() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Identity</div>
        <div style="color: #2774a7; font-size: 16px"><?= $author->getIdentity() ?></div>
    </div>
    <div>
        <div style="font-weight: bold; font-size: 24px; color: #0A246A">Book</div>
        <div style="color: #2774a7; font-size: 16px"><?=$book->getBook() ?></div>
    </div>
</div>

<br>

<img src="<?= $author->getImage()?>"/>


